### ISSUE TITLE
How to Handle Actions i.e. POST, PUT, DELETE HTTP Methods

### ISSUE THREAD

**Issue by RehanSaeed** [smizell/restfuljson#16]
I really like the idea of restful JSON and think it's a distinct improvement over other formats like HAL where URL's are grouped together. Restful JSON handles GET URL's quite happily. 

My question is about how to deal with actions, this is something that HAL also ignores but Hydra addresses but with much greater complexity. Is there anything to say on this subject?

**Comment by smizell** [comment]
Thanks for the question! This is a great topic, and it's probably one we should clarify more. 

In RESTful JSON, we only provide ways to include links. In the world of link relations, though, links can provide more than just safe GET requests. For instance, if you look at the [edit link relation](https://tools.ietf.org/html/rfc5023#section-11.1), you'll see that an `edit` link means the user can retrieve, update, or delete the resource. In RESTful JSON, you could do the same thing with an `edit_url` and then explain in your documentation that this maps to the link relation type `edit`.

What I've recommended to people is to just have one affordance per link in RESTful JSON. While the `edit` rel above has three possible actions, I recommend people to just use one per link as this allows for more granularity. You might have `url` (for itself), `update_url`, and `delete_url`.

Where this differs is that formats like [Siren](https://github.com/kevinswiber/siren) have stronger support for actions, where you can define fields and values at runtime. I love this approach, but it's not something that currently fits into RESTful JSON. However, given that we support extending RESTful JSON with profiles, you are free to add your own actions if that's a requirement.

I hope that helps. Happy to continue the discussion if you have more thoughts and questions!

**Comment by RehanSaeed** [comment]
`update_url` and `delete_url` sounds sensible, assuming you document that `update` means POST or PUT. Why not use the HTTP verbs themselves?

I've looked at Siren but it's verbose, less pragmatic and it looks like the metadata ate the actual JSON content. Hydra is very similar in that regard.

REST'ful JSON is probably most similar to [JSON-LD](https://json-ld.org/) if you remove the `@` signs and add the word `url`.

Choosing a hypermedia format is hard, there are so many out there, very little in the way of frameworks supporting the creation of API's using them, which is why I think the simpler formats like this one have more of a chance to catch on.

Who backs REST'ful JSON, what made you decide to add yet another format into the wild?

**Comment by smizell** [comment]
> update_url and delete_url sounds sensible, assuming you document that update means POST or PUT. Why not use the HTTP verbs themselves?

You hit on the important detail—you must document the links somewhere. A link requires context and some relation type, so you need documentation somewhere that says something like, "When you invoke the `update_url`, use the PUT HTTP method."

You are free to use the HTTP methods if you like, but I think it's better to define your application semantics and then map HTTP methods to those. This lets you go beyond CRUD. For instance, if you were building a TODO application, you could have `mark_complete_url` to mark a todo complete, and then a `mark_incomplete_url` to mark it incomplete. In this situation, the links give possible state transitions that CRUD cannot do, and it guides the API client on what it can and cannot do based on the presence and absence of links.

> Who backs REST'ful JSON, what made you decide to add yet another format into the wild?

It was put together by Mark W. Foster (@fosrias) and me. It came from a need to use hypermedia without requiring people to move away from their normal toolset. Right now, it's difficult to use tools like OpenAPI (formerly Swagger) with hypermedia just because of the nature of generic formats like HAL or Siren.

It also arose out of the observation that this is what people are already doing. If you look at GitHub's API and several others listed on [the site](http://restfuljson.org/), you'll see people already doing this method—it just didn't have a name. So we gave it one! :)

> Choosing a hypermedia format is hard, there are so many out there, very little in the way of frameworks supporting the creation of API's using them, which is why I think the simpler formats like this one have more of a chance to catch on.

This was the big reason for us to put RESTful JSON together. Hypermedia is currently difficult, and the gap between what people are doing and what hypermedia prescribes is large. RESTful JSON says to just add some properties to your existing JSON and gain the benefits.

**Comment by smizell** [comment]
I'm going to close for now, but am always happy to answer any questions. Thanks again!
